import 'bootstrap/dist/css/bootstrap.min.css';
import Script from 'next/script';
import { avenirNext } from "@/fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Pure blue surf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={avenirNext.className}>{children}</body>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></Script>
    </html>
  );
}
